export const ErrorCodes = {
  AUDIO_FILE_EMPTY: "AUDIO_FILE_EMPTY",
  AUDIO_INVALID_TYPE: "AUDIO_INVALID_TYPE",
  AUDIO_FILE_READ_FAILED: "AUDIO_FILE_READ_FAILED",
  AUDIO_DECODE_FAILED: "AUDIO_DECODE_FAILED",
  AUDIO_RESAMPLE_INVALID_RATE: "AUDIO_RESAMPLE_INVALID_RATE",
  MODEL_FILE_EMPTY: "MODEL_FILE_EMPTY",
  MODEL_UNSUPPORTED_FORMAT: "MODEL_UNSUPPORTED_FORMAT",
  MODEL_READ_FAILED: "MODEL_READ_FAILED",
  MODEL_CONVERTER_UNAVAILABLE: "MODEL_CONVERTER_UNAVAILABLE",
  MODEL_CONVERSION_FAILED: "MODEL_CONVERSION_FAILED",
  MODEL_VERIFY_SESSION_FAILED: "MODEL_VERIFY_SESSION_FAILED",
  MODEL_VERIFY_RUN_FAILED: "MODEL_VERIFY_RUN_FAILED",
  MODEL_VERIFY_UNSUPPORTED_INPUT: "MODEL_VERIFY_UNSUPPORTED_INPUT",
  SYNTH_FEED_BUILD_FAILED: "SYNTH_FEED_BUILD_FAILED",
  SYNTH_INFERENCE_FAILED: "SYNTH_INFERENCE_FAILED",
  SYNTH_OUTPUT_PARSE_FAILED: "SYNTH_OUTPUT_PARSE_FAILED",
  FEATURE_MODEL_LOAD_FAILED: "FEATURE_MODEL_LOAD_FAILED",
  FEATURE_PREPROCESS_FAILED: "FEATURE_PREPROCESS_FAILED",
  FEATURE_INFERENCE_FAILED: "FEATURE_INFERENCE_FAILED",
  FEATURE_INVALID_AUDIO: "FEATURE_INVALID_AUDIO",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
