export const ErrorCodes = {
  FILE_EMPTY: "AUDIO_FILE_EMPTY",
  INVALID_TYPE: "AUDIO_INVALID_TYPE",
  FILE_READ_FAILED: "AUDIO_FILE_READ_FAILED",
  DECODE_FAILED: "AUDIO_DECODE_FAILED",
  RESAMPLE_INVALID_RATE: "AUDIO_RESAMPLE_INVALID_RATE",
  MODEL_UNSUPPORTED_FORMAT: "MODEL_UNSUPPORTED_FORMAT",
  MODEL_READ_FAILED: "MODEL_READ_FAILED",
  MODEL_CONVERTER_UNAVAILABLE: "MODEL_CONVERTER_UNAVAILABLE",
  MODEL_CONVERSION_FAILED: "MODEL_CONVERSION_FAILED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
