export const ErrorCodes = {
  AUDIO_FILE_EMPTY: "AUDIO_FILE_EMPTY",
  AUDIO_INVALID_TYPE: "AUDIO_INVALID_TYPE",
  AUDIO_FILE_READ_FAILED: "AUDIO_FILE_READ_FAILED",
  AUDIO_DECODE_FAILED: "AUDIO_DECODE_FAILED",
  AUDIO_RESAMPLE_INVALID_RATE: "AUDIO_RESAMPLE_INVALID_RATE",
  MODEL_FILE_EMPTY: "MODEL_FILE_EMPTY",
  MODEL_UNSUPPORTED_FORMAT: "MODEL_UNSUPPORTED_FORMAT",
  MODEL_READ_FAILED: "MODEL_READ_FAILED",
  MODEL_CONVERTER_UNAVAILABLE: "MODEL_CONVERTER_UNAVAILABLE",
  MODEL_CONVERSION_FAILED: "MODEL_CONVERSION_FAILED",
  MODEL_VERIFY_SESSION_FAILED: "MODEL_VERIFY_SESSION_FAILED",
  MODEL_VERIFY_RUN_FAILED: "MODEL_VERIFY_RUN_FAILED",
  MODEL_VERIFY_UNSUPPORTED_INPUT: "MODEL_VERIFY_UNSUPPORTED_INPUT",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
